# docker-compose.yml 

services:
  transcriber:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
      - ./database:/app/database
    env_file:
      - .env
    environment:
      - DEFAULT_TRANSCRIBE_API=gpt4o # Set your desired default API here ("assemblyai", "gpt4o" or "whisper")
      - DEFAULT_LANGUAGE=auto # Set your desired default language here ("en", "nl", "fr", "es", or "auto")
    restart: unless-stopped