# docker-compose.yml 

services:
  transcriber:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
      - ./database:/app/database
    env_file:
      - .env
    environment:
      - DEFAULT_TRANSCRIBE_API=gpt4o
      - DEFAULT_LANGUAGE=auto
    restart: unless-stopped